# -*- coding: utf-8 -*-
"""專題報告程式

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15IzttV7U_YfPRN3kJyEVZbkcZyI0LwCY

# **-----資料預處理-----**
"""
import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

"""## 從雲端複製到本地"""

import os, glob, random, shutil, re
from concurrent.futures import ThreadPoolExecutor, as_completed

# ====== 基本設定 ======
random.seed(42)

SRC_ROOT = '/content/drive/MyDrive/Special_Topic'
DST_ROOT = 'P2'
IMG_DIRNAME  = 'TRUE'
MASK_DIRNAME = 'FALSE'
DST_MASK_DIRNAME = 'FAKE'
PATTERN = '*.png'
MAX_WORKERS = 8    # 複製時的執行緒數
DEFAULT_QUOTA = 0   # 預設每類抽幾張（若無規則匹配）

EXACT_QUOTA = {
    'whitening': 1000,
    'smoothing': 1000,
    'facelifting': 1000,
    "eye": 1000,
    'three': 3000,
    'four': 3000,
}
# ====== 測試用 ======
# EXACT_QUOTA = {
#     'whitening': 10,
#     'smoothing': 10,
#     'facelifting': 10,
#     "eye": 10,
#     'three': 10,
#     'four': 10,
# }
REGEX_QUOTA = []

# ====== 工具函式 ======
def list_first_level_dirs(root):
    return sorted([d for d in os.listdir(root)
                   if os.path.isdir(os.path.join(root, d))])

def collect_pairs(img_folder, mask_folder, pattern):
    imgs  = {os.path.basename(p): p for p in glob.glob(os.path.join(img_folder, pattern))}
    masks = {os.path.basename(p): p for p in glob.glob(os.path.join(mask_folder, pattern))}
    common = sorted(set(imgs) & set(masks))
    return imgs, masks, common

def safe_copy(src, dst_dir):
    os.makedirs(dst_dir, exist_ok=True)
    dst = os.path.join(dst_dir, os.path.basename(src))
    shutil.copyfile(src, dst)
    return dst

def quota_for(category_name: str) -> int:
    if category_name in EXACT_QUOTA:
        return EXACT_QUOTA[category_name]
    for pat, cnt in REGEX_QUOTA:
        if re.search(pat, category_name, flags=re.IGNORECASE):
            return cnt
    return DEFAULT_QUOTA

# ====== 主流程 ======
categories = list_first_level_dirs(SRC_ROOT)
if not categories:
    raise RuntimeError(f'來源資料夾沒有任何子資料夾：{SRC_ROOT}')

summary = {}

with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
    futures = []

    for cat in categories:
        src_img_folder  = os.path.join(SRC_ROOT, cat, IMG_DIRNAME)
        src_mask_folder = os.path.join(SRC_ROOT, cat, MASK_DIRNAME)

        if not (os.path.isdir(src_img_folder) and os.path.isdir(src_mask_folder)):
            print(f'略過「{cat}」：找不到子資料夾 {IMG_DIRNAME}/ 或 {MASK_DIRNAME}/')
            continue

        imgs, masks, common = collect_pairs(src_img_folder, src_mask_folder, PATTERN)
        if len(common) == 0:
            print(f'略過「{cat}」：{IMG_DIRNAME} 與 {MASK_DIRNAME} 沒有共同檔名')
            continue

        quota = quota_for(cat)
        n = min(quota, len(common))
        chosen = random.sample(common, n)

        dst_img_folder  = os.path.join(DST_ROOT, cat, IMG_DIRNAME)
        dst_mask_folder = os.path.join(DST_ROOT, cat, DST_MASK_DIRNAME)
        os.makedirs(dst_img_folder, exist_ok=True)
        os.makedirs(dst_mask_folder, exist_ok=True)

        for name in chosen:
            futures.append(ex.submit(safe_copy, imgs[name],  dst_img_folder))
            futures.append(ex.submit(safe_copy, masks[name], dst_mask_folder))

        summary[cat] = n
        print(f'類別「{cat}」：規則目標 {quota} 張，可用 {len(common)} 張，實際抽 {n} 張')

    for _ in as_completed(futures):
        pass

# ====== 總結 ======
total_pairs = sum(summary.values())
print('====== 複製完成 ======')
for cat, cnt in summary.items():
    print(f'分類「{cat}」：{cnt} 對')
print(f'總計：{total_pairs} 對（影像與標註各 {total_pairs} 張）')
print(f'輸出根目錄：{os.path.abspath(DST_ROOT)}')

"""## 全部處理 ##"""

import os
import cv2
import glob
import numpy as np

ROOT = 'P2'
IMG_DIR = 'TRUE'    # 原圖
FAKE_DIR = 'FAKE'   # 修圖
PATTERN = '*.png'
SIZE = (256, 256)

IMAGES  = []   # 原圖
IMAGES2 = []   # 修圖
CATS    = []   # 記錄每張圖屬於哪個類別
NAMES   = []   # 記錄檔名

def list_categories(root):
    return sorted([d for d in os.listdir(root) if os.path.isdir(os.path.join(root, d))])

def collect_map(folder, pattern):
    return {os.path.basename(p): p for p in glob.glob(os.path.join(folder, pattern))}

for cat in list_categories(ROOT):
    before_dir = os.path.join(ROOT, cat, IMG_DIR)
    after_dir  = os.path.join(ROOT, cat, FAKE_DIR)

    if not (os.path.isdir(before_dir) and os.path.isdir(after_dir)):
        print(f'略過「{cat}」：找不到 {IMG_DIR}/ 或 {FAKE_DIR}/')
        continue

    imgs  = collect_map(before_dir, PATTERN)
    fakes = collect_map(after_dir,  PATTERN)

    common = sorted(set(imgs) & set(fakes))
    if not common:
        print(f'類別「{cat}」沒有同名成對檔案')
        continue

    for name in common:
        p_before = imgs[name]
        p_after  = fakes[name]

        before_img = cv2.imread(p_before)
        after_img  = cv2.imread(p_after)
        if before_img is None or after_img is None:
            print(f'讀取失敗（{cat}/{name}）')
            continue

        # 統一大小
        before_img = cv2.resize(before_img, SIZE)
        after_img  = cv2.resize(after_img,  SIZE)

        IMAGES.append(before_img)
        IMAGES2.append(after_img)
        CATS.append(cat)
        NAMES.append(name)

IMAGES  = np.array(IMAGES)
IMAGES2 = np.array(IMAGES2)

print(f'收集完成：{len(IMAGES)} 對')

"""# **-----開始訓練模型-----**"""

import torch
from torch import nn

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

"""# ---**model部分**---

# **model**
"""

import functools
import torch
import torch.nn as nn
import torch.nn.functional as F


# =======================
# pixel2pixel
# =======================
class Generator(nn.Module):
    def __init__(self, in_num_ch=3, out_num_ch=3, first_num_ch=32, input_size=256): # 32
        super(Generator, self).__init__()

        self.down_1 = nn.Sequential(
            nn.Conv2d(in_num_ch, first_num_ch, 4, 2, padding=1),
            nn.LeakyReLU(0.2)
        )
        self.down_2 = ConvBlock(first_num_ch, 2*first_num_ch)
        self.down_3 = ConvBlock(2*first_num_ch, 4*first_num_ch)
        self.down_4 = ConvBlock(4*first_num_ch, 8*first_num_ch)
        self.down_5 = ConvBlock(8*first_num_ch, 8*first_num_ch)
        self.down_6 = ConvBlock(8*first_num_ch, 8*first_num_ch, activation='no')


        self.bottleneck = nn.Sequential(
            ResBlock(8*first_num_ch, dilation=1),
            ResBlock(8*first_num_ch, dilation=2),
            ResBlock(8*first_num_ch, dilation=3),
            ResBlock(8*first_num_ch, dilation=1),
        )


        self.up_5 = DeconvBlock(8*first_num_ch, 8*first_num_ch)
        self.up_4 = DeconvBlock(16*first_num_ch, 8*first_num_ch)
        self.up_3 = DeconvBlock(16*first_num_ch, 4*first_num_ch)
        self.up_2 = DeconvBlock(8*first_num_ch, 2*first_num_ch)
        self.up_1 = DeconvBlock(4*first_num_ch, first_num_ch)

        self.output = DeconvBlock(2*first_num_ch, out_num_ch, is_last=True)
        self.output_act = nn.Tanh()
        # self.output_act = nn.Sigmoid()


    def forward(self, x):
        down_1 = self.down_1(x)
        down_2 = self.down_2(down_1)
        down_3 = self.down_3(down_2)
        down_4 = self.down_4(down_3)
        down_5 = self.down_5(down_4)
        down_6 = self.down_6(down_5)


        d = self.bottleneck(down_6)

        up_5 = self.up_5(down_5, d)
        up_4 = self.up_4(down_4, up_5)
        up_3 = self.up_3(down_3, up_4)
        up_2 = self.up_2(down_2, up_3)
        up_1 = self.up_1(down_1, up_2)
        output = self.output(None, up_1)
        output_act = self.output_act(output)
        return output_act

class ConvBlock(nn.Module):
    def __init__(self, in_num_ch, out_num_ch, filter_size=4, stride=2, padding=1, activation='lrelu', norm='in'):
        super(ConvBlock, self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_num_ch, out_num_ch, filter_size, stride, padding=padding),
            )
        if norm == 'bn':
            self.act = nn.BatchNorm2d(out_num_ch)
        elif norm == 'in':
            self.act = nn.InstanceNorm2d(out_num_ch, affine=True)

        if activation == 'lrelu':
            self.act2 = nn.LeakyReLU(0.2)
        else:
            self.act2 = nn.Sequential()

    def forward(self, x):
        x = self.conv(x)
        x = self.act(x)
        x = self.act2(x)
        return x

class ResBlock(nn.Module):
    def __init__(self, ch, dilation=1, norm='in'):
        super().__init__()
        pad = dilation
        layers = [
            nn.Conv2d(ch, ch, 3, 1, padding=pad, dilation=dilation, bias=(norm is None)),
            nn.InstanceNorm2d(ch, affine=True) if norm=='in' else nn.BatchNorm2d(ch),
            nn.ReLU(),
            nn.Conv2d(ch, ch, 3, 1, padding=pad, dilation=dilation, bias=(norm is None)),
            nn.InstanceNorm2d(ch, affine=True) if norm=='in' else nn.BatchNorm2d(ch),
        ]
        self.block = nn.Sequential(*layers)

    def forward(self, x):
        return F.relu(x + self.block(x))

class DeconvBlock(nn.Module):
    def __init__(self, in_num_ch, out_num_ch, filter_size=3, stride=1, padding=1,
                 activation='lrelu', norm='in', is_last=False):
        super(DeconvBlock, self).__init__()

        if activation == 'lrelu':
            self.act = nn.LeakyReLU(0.2)
        elif activation == 'relu':
            self.act = nn.ReLU()
        else:
            self.act = nn.Sequential()

        self.is_last = is_last

        self.up = nn.Sequential(
            nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True),
            nn.Conv2d(in_num_ch, out_num_ch, filter_size, stride, padding=padding)
        )

        if not is_last:
            self.bn = nn.InstanceNorm2d(out_num_ch, affine=True) if norm == 'in' else nn.BatchNorm2d(out_num_ch)

    def forward(self, x_down, x_up):
        x_up = self.act(x_up)
        x_up = self.up(x_up)

        if not self.is_last:
            x_up = self.bn(x_up)
            x = torch.cat([x_down, x_up], 1)
        else:
            x = x_up

        return x

# =======================
# Discriminator
# =======================
class Discriminator(nn.Module):
    def __init__(self, in_num_ch=6, first_num_ch=32):
        super(Discriminator, self).__init__()
        self.conv_1 = nn.Sequential(
            nn.Conv2d(in_num_ch, first_num_ch, 4, 2, padding=1),
            nn.LeakyReLU(0.2)
        )
        self.conv_2 = ConvBlock(first_num_ch, 2 * first_num_ch, norm='in')
        self.conv_3 = ConvBlock(2 * first_num_ch, 4 * first_num_ch, norm='in')
        self.conv_4 = ConvBlock(4 * first_num_ch, 8 * first_num_ch, norm='in')
        self.conv_5 = ConvBlock(8 * first_num_ch, 8 * first_num_ch, stride=1)

        self.output = nn.Conv2d(8 * first_num_ch, 1, 4)
        self.output_act = nn.Sigmoid()

    def forward(self, x, return_feats=False):
        conv_1 = self.conv_1(x)
        conv_2 = self.conv_2(conv_1)
        conv_3 = self.conv_3(conv_2)
        conv_4 = self.conv_4(conv_3)
        conv_5 = self.conv_5(conv_4)

        output = self.output(conv_5)
        # output = self.output_act(output) # 保持原樣 (LSGAN 不用 Sigmoid)

        if return_feats:
            return output, [conv_1, conv_2, conv_3, conv_4, conv_5]
        else:
            return output

# =======================
# CBAM
# =======================
class CBAM(nn.Module):

    def __init__(self, n_channels_in, reduction_ratio, kernel_size):
        super(CBAM, self).__init__()
        self.n_channels_in = n_channels_in
        self.reduction_ratio = reduction_ratio
        self.kernel_size = kernel_size

        self.channel_attention = ChannelAttention(n_channels_in, reduction_ratio)
        self.spatial_attention = SpatialAttention(kernel_size)

    def forward(self, f):
        chan_att = self.channel_attention(f)
        # print(chan_att.size())
        fp = chan_att * f
        # print(fp.size())
        spat_att = self.spatial_attention(fp)
        # print(spat_att.size())
        fpp = spat_att * fp
        # print(fpp.size())
        return fpp


class SpatialAttention(nn.Module):
    def __init__(self, kernel_size):
        super(SpatialAttention, self).__init__()
        self.kernel_size = kernel_size

        assert kernel_size % 2 == 1, "Odd kernel size required"
        self.conv = nn.Conv2d(in_channels = 2, out_channels = 1, kernel_size = kernel_size, padding= int((kernel_size-1)/2))


    def forward(self, x):
        max_pool, _ = torch.max(x, dim = 1, keepdim = True)
        avg_pool = torch.mean(x, dim = 1, keepdim = True)
        pool = torch.cat([max_pool, avg_pool], dim = 1)
        conv = self.conv(pool)
        att = torch.sigmoid(conv)

        return att

class ChannelAttention(nn.Module):
    def __init__(self, n_channels_in, reduction_ratio):
        super().__init__()
        c = n_channels_in
        r = max(1, int(c / float(reduction_ratio)))

        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)

        self.mlp = nn.Sequential(
            nn.Conv2d(c, r, kernel_size=1, bias=False),
            nn.ReLU(inplace=True),
            nn.Conv2d(r, c, kernel_size=1, bias=False),
        )

    def forward(self, x):
        att = self.mlp(self.avg_pool(x)) + self.mlp(self.max_pool(x))  # (B,C,1,1)
        return torch.sigmoid(att)

# =======================
# RRDB
# =======================
def make_layer(block, n_layers):
    return nn.Sequential(*[block() for _ in range(n_layers)])

class ResidualDenseBlock_5C(nn.Module):
    def __init__(self, nf=32, gc=32, bias=True):
        super().__init__()
        self.conv1 = nn.Conv2d(nf, gc, 3, 1, 1, bias=bias)
        self.conv2 = nn.Conv2d(nf + gc, gc, 3, 1, 1, bias=bias)
        self.conv3 = nn.Conv2d(nf + 2*gc, gc, 3, 1, 1, bias=bias)
        self.conv4 = nn.Conv2d(nf + 3*gc, gc, 3, 1, 1, bias=bias)
        self.conv5 = nn.Conv2d(nf + 4*gc, nf, 3, 1, 1, bias=bias)
        self.cbma = CBAM(nf, 8, 5)

        self.lrelu = nn.LeakyReLU(0.2, inplace=True)
    def forward(self, x):
        x1 = self.lrelu(self.conv1(x))
        x2 = self.lrelu(self.conv2(torch.cat([x, x1], 1)))
        x3 = self.lrelu(self.conv3(torch.cat([x, x1, x2], 1)))
        x4 = self.lrelu(self.conv4(torch.cat([x, x1, x2, x3], 1)))
        x5 = self.conv5(torch.cat([x, x1, x2, x3, x4], 1))
        x5 = self.cbma(x5)
        return x + 0.2 * x5

class RRDB(nn.Module):
    def __init__(self, nf, gc=32):
        super().__init__()
        self.b1 = ResidualDenseBlock_5C(nf, gc)
        self.b2 = ResidualDenseBlock_5C(nf, gc)
        self.b3 = ResidualDenseBlock_5C(nf, gc)
    def forward(self, x):
        return x + 0.2 * self.b3(self.b2(self.b1(x)))

class RRDBRefineNet(nn.Module):

    def __init__(self, in_nc=6, out_nc=3, nf=32, nb=3, gc=32):
        super().__init__()
        RRDB_block = functools.partial(RRDB, nf=nf, gc=gc)
        self.head = nn.Conv2d(in_nc, nf, 3, 1, 1)
        self.trunk = make_layer(RRDB_block, nb)
        self.trunk_conv = nn.Conv2d(nf, nf, 3, 1, 1)
        self.tail = nn.Conv2d(nf, out_nc, 3, 1, 1)

    def forward(self, x, y_coarse):
        inp = torch.cat([x, y_coarse], dim=1)

        fea = self.head(inp)
        trunk = self.trunk_conv(self.trunk(fea))
        fea = fea + trunk
        r = self.tail(fea)

        y_hat = (y_coarse + r).clamp(-1, 1)
        return y_hat, r

"""# **loss part1**"""

from tqdm import tqdm
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torchvision import models

# =======================
# PerceptualLoss
# =======================
class PerceptualLoss(nn.Module):
    '''
    content loss and style loss extracted by selected model
    '''
    def __init__(self, device, model_type='vgg19', content_layers=['conv_2', 'conv_3'],
                style_layers=['conv_1', 'conv_2', 'conv_3', 'conv_4', 'conv_5'], channel_idx=0):
        super(PerceptualLoss, self).__init__()
        self.device = device
        self.model_type = model_type
        self.content_layers = content_layers
        self.style_layers = style_layers
        self.channel_idx = channel_idx

        vgg = models.vgg19(weights=models.VGG19_Weights.DEFAULT).features
        for i, m in enumerate(vgg):
            if isinstance(m, nn.ReLU):
                vgg[i] = nn.ReLU(inplace=False)
        self.model = vgg.to(device).eval()
        for p in self.model.parameters():
            p.requires_grad = False

    def normalize_image(self, image):
        # [-1,1] (tanh 輸出) → [0,1]
        image = (image + 1) / 2
        image = image.clamp(0, 1)
        # # grayscale to rgb
        # image = image[:, self.channel_idx, :, :]
        # image = image.unsqueeze(1).expand(-1, 3, -1, -1)

        # normalize by mean/std
        mean = torch.tensor([0.485, 0.456, 0.406]).view(-1, 1, 1).to(self.device)
        std = torch.tensor([0.229, 0.224, 0.225]).view(-1, 1, 1).to(self.device)


        # resize 到 224x224
        if image.shape[-2:] != (224, 224):
            image = F.interpolate(image, size=(224, 224), mode='bilinear', align_corners=False)

        # ImageNet normalize
        image = (image - mean) / std
        return image

    def content_loss(self, feature_prediction, feature_target):
        content_loss = F.mse_loss(feature_prediction, feature_target)

        return content_loss

    def style_loss(self, feature_prediction, feature_target):
        gram_prediction = self.gram_matrix(feature_prediction)
        gram_target = self.gram_matrix(feature_target)
        style_loss = F.mse_loss(gram_prediction, gram_target)

        return style_loss

    def gram_matrix(self, feat):
        b, c, h, w = feat.size()
        f = feat.view(b, c, h*w)
        G = torch.bmm(f, f.transpose(1, 2))
        return G / (c*h*w)

    # 不使用
    # def gram_matrix(self, feature):
    #     batch_size, num_ch, height, width = feature.size()  # NCHW
    #     feature = feature.view(batch_size * num_ch, height * width)
    #     gram = torch.mm(feature, feature.t())

    #     return gram.div(batch_size * num_ch * height * width)

    def forward(self, prediction, target):
        prediction = self.normalize_image(prediction)
        target = self.normalize_image(target)

        conv_block_idx = 0
        model_new = nn.Sequential().to(self.device)
        content_losses = []
        # style_losses = []
        feature_prediction = prediction
        feature_target = target

        for i, layer in enumerate(self.model):
            feature_prediction = layer(feature_prediction)
            feature_target = layer(feature_target)
            if isinstance(layer, nn.Conv2d):
                conv_block_idx += 1
                name = 'conv_' + str(conv_block_idx)
                if name in self.content_layers:
                    content_losses.append(self.content_loss(feature_prediction, feature_target))
                # if name in self.style_layers:
                #     style_losses.append(self.style_loss(feature_prediction, feature_target))

        return content_losses

"""# **loss part2**"""

!pip install lpips

import torch
import torch.nn as nn
import torch.nn.functional as F

# =======================
# GANLoss
# =======================
class GANLoss(nn.Module):
    def __init__(self, device, ls_gan=True):
        super(GANLoss, self).__init__()
        self.device = device
        if ls_gan == True:
            self.loss = nn.MSELoss()
        else:
            self.loss = nn.BCELoss()

    def forward(self, prediction, target_label_value=1.):
        target_label = torch.tensor(target_label_value).to(self.device)
        target = target_label.expand_as(prediction)
        loss = self.loss(prediction, target)
        return loss

class ResidualLoss(nn.Module):
    """
    Residual Loss for Stage-2 Refiner
    r       : residual predicted by G2
    y_hat   : refined output = y_coarse + r
    y       : ground truth (target image)
    y_coarse: coarse output from G1
    """
    def __init__(self, criterion=nn.L1Loss()):
        super(ResidualLoss, self).__init__()
        self.criterion = criterion

    def forward(self, r, y_hat, y, y_coarse):
        r_gt = (y - y_coarse).detach()
        l_res = self.criterion(r, r_gt)

        l_l1  = self.criterion(y_hat, y)
        return l_res, l_l1

class SobelEdgeLoss(nn.Module):
    def __init__(self, mode='mag', loss='l1', eps=1e-6):
        """
        mode: 'mag' | 'xy'    # 比較梯度幅值或同時比較 Gx/Gy
        loss: 'l1' | 'charb'  # L1 或 Charbonnier
        """
        super().__init__()
        self.mode, self.loss, self.eps = mode, loss, eps
        kx = torch.tensor([[1,0,-1],[2,0,-2],[1,0,-1]], dtype=torch.float32).view(1,1,3,3)
        ky = torch.tensor([[1,2,1],[0,0,0],[-1,-2,-1]], dtype=torch.float32).view(1,1,3,3)
        self.register_buffer('kx', kx)
        self.register_buffer('ky', ky)

    def _grad(self, x):
        c = x.size(1)
        kx = self.kx.repeat(c,1,1,1)
        ky = self.ky.repeat(c,1,1,1)
        gx = F.conv2d(x, kx, padding=1, groups=c)
        gy = F.conv2d(x, ky, padding=1, groups=c)
        if self.mode == 'xy':
            return gx, gy
        # 幅值
        mag = torch.sqrt(gx*gx + gy*gy + self.eps)
        return mag

    def _l(self, a, b):
        if self.loss == 'l1':
            return F.l1_loss(a, b)
        return torch.mean(torch.sqrt((a-b)**2 + self.eps))

    def forward(self, out, gt):
        # out, gt: (N,C,H,W)，範圍 [-1,1] 或 [0,1] 都可（兩邊一致即可）
        if self.mode == 'xy':
            gx_o, gy_o = self._grad(out)
            gx_g, gy_g = self._grad(gt)
            return 0.5 * (self._l(gx_o, gx_g) + self._l(gy_o, gy_g))
        else:
            mag_o = self._grad(out)
            mag_g = self._grad(gt)
            return self._l(mag_o, mag_g)

class LaplacianEdgeLoss(nn.Module):
    def __init__(self, loss='l1'):
        super().__init__()
        self.loss = loss
        k = torch.tensor([[0,1,0],[1,-4,1],[0,1,0]], dtype=torch.float32).view(1,1,3,3)
        self.register_buffer('k', k)

    def _l(self, a, b):
        if self.loss == 'l1':
            return F.l1_loss(a,b)
        return torch.mean(torch.sqrt((a-b)**2 + 1e-6))

    def forward(self, out, gt):
        c = out.size(1)
        k = self.k.repeat(c,1,1,1)
        lo = F.conv2d(out, k, padding=1, groups=c)
        lg = F.conv2d(gt,  k, padding=1, groups=c)
        return self._l(lo, lg)

def feature_matching_loss(feats_fake, feats_real):
    return sum(F.l1_loss(f_fake, f_real.detach()) for f_fake, f_real in zip(feats_fake, feats_real))

def fft_highfreq_loss(pred, target, hp_ratio=0.5):
    # pred/target: (N,C,H,W), [-1,1] or [0,1] (一致即可)
    N, C, H, W = pred.shape
    P = torch.fft.rfft2(pred, norm='ortho')
    T = torch.fft.rfft2(target, norm='ortho')

    # 建立高頻權重遮罩（以半徑比 hp_ratio 作為分界）
    yy, xx = torch.meshgrid(torch.arange(H, device=pred.device),
                            torch.arange(W//2+1, device=pred.device), indexing='ij')
    cy, cx = H//2, 0
    r = torch.sqrt(((yy-cy)/(H/2))**2 + ((xx-cx)/(W/2))**2)  # 0~1
    w = torch.clamp((r - hp_ratio) / (1 - hp_ratio), 0, 1)   # 低頻0→高頻1
    w = w.view(1,1,H,W//2+1)

    loss = torch.mean(torch.abs(P - T) * w)
    return loss

"""# **dataset**"""

from torch.utils.data import Dataset
from torchvision import transforms
from PIL import Image
import os

class UnetDataset(Dataset):
    def __init__(self, images, images2, image_size=(256, 256)):
        self.images = images
        self.images2 = images2

        self.transform_img = transforms.Compose([
            transforms.Resize(image_size),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
        ])
        self.transform_img2 = transforms.Compose([
            transforms.Resize(image_size),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
        ])

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        image = self.images[idx]
        image2 = self.images2[idx]

        if isinstance(image, np.ndarray):
            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            image = Image.fromarray(image)
        if isinstance(image2, np.ndarray):
            image2 = cv2.cvtColor(image2, cv2.COLOR_BGR2RGB)
            image2 = Image.fromarray(image2)

        image = self.transform_img(image)
        image2 = self.transform_img2(image2)

        return image, image2

import torch.nn.functional as F
import torch
import torch.nn as nn
import torchvision.transforms as transforms
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader

train_images2, temp_images2, train_images, temp_images = train_test_split(
    IMAGES2, IMAGES, test_size=0.05, random_state=42
)

# val_images2, test_images2, val_images, test_images = train_test_split(
#     temp_images2, temp_images, test_size=0.5, random_state=42
# )

train_dataset = UnetDataset(images=train_images, images2=train_images2)
# val_dataset   = UnetDataset(images=val_images, images2=val_images2)
# test_dataset  = UnetDataset(images=test_images, images2=test_images2)


train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True, num_workers=12, pin_memory=True) # 16
# val_loader   = DataLoader(val_dataset, batch_size=1, shuffle=False)
# test_loader  = DataLoader(test_dataset, batch_size=1, shuffle=False)

"""# **train**

# **皮膚剝離**
"""

!git clone https://github.com/zllrunning/face-parsing.PyTorch.git

import sys
sys.path.append("face-parsing.PyTorch")
from model import BiSeNet

"""# **高森**"""

import sys, torch, torch.nn.functional as F
from pathlib import Path
from PIL import Image
import torchvision.transforms as T
import matplotlib.pyplot as plt

# =======================
# 專案與權重路徑
# =======================
REPO_DIR = Path("face-parsing.PyTorch")   # 你的 clone 路徑
WEIGHT_FILE = Path("79999_iter.pth")      # 權重檔（可放同工作目錄）
repo_path = str(REPO_DIR.resolve())
if repo_path not in sys.path:
    sys.path.append(repo_path)

from model import BiSeNet

def load_face_parser(device, weight_path):
    net = BiSeNet(n_classes=19)
    state = torch.load(str(weight_path), map_location=device)
    net.load_state_dict(state)
    net.eval().to(device)
    return net

parser = load_face_parser(device, WEIGHT_FILE)


def to01(x):  return (x * 0.5 + 0.5).clamp(0, 1)

# =======================
# 反高斯模糊
# =======================
def gaussian_kernel(kernel_size=5, sigma=1.0, channels=3):
    x_coord = torch.arange(kernel_size, device=device, dtype=torch.float32)
    x_grid = x_coord.repeat(kernel_size).view(kernel_size, kernel_size)
    y_grid = x_grid.t()
    xy_grid = torch.stack([x_grid, y_grid], dim=-1).float()

    mean = (kernel_size - 1) / 2.
    variance = sigma ** 2.

    gk = (1./(2.*torch.pi*variance)) * torch.exp(-torch.sum((xy_grid - mean) ** 2., dim=-1) / (2*variance))
    gk = gk / gk.sum()
    gk = gk.view(1, 1, kernel_size, kernel_size)
    gk = gk.repeat(channels, 1, 1, 1)
    return gk

def gaussian_blur_torch(x, sigma=1.0):
    kernel_size = int(2 * round(3 * sigma) + 1)
    kernel = gaussian_kernel(kernel_size, sigma, x.size(1)).to(x.device)
    padding = kernel_size // 2
    x_blur = F.conv2d(x, kernel, padding=padding, groups=x.size(1))
    return x_blur

def desoften(img, alpha=0.3, steps=5, sigma=0.7):
    I = img.clone()
    for _ in range(steps):
        I_blur = gaussian_blur_torch(I, sigma)
        I = img + alpha * (img - I_blur)
        I = torch.clamp(I, -1, 1)
    return I


# =======================
# 抓皮膚區域
# =======================
@torch.no_grad()
def get_skin_mask(parser, img01):
    resize = T.Resize((512, 512))
    ir = resize(img01)
    logits = parser(ir)[0]
    parsing = logits.argmax(1, keepdim=True)
    mask = (parsing == 1).float()
    mask = F.interpolate(mask, size=img01.shape[-2:], mode='bilinear', align_corners=False)
    mask = F.avg_pool2d(mask, kernel_size=5, stride=1, padding=2)
    return mask.clamp(0, 1)

"""# **使用AMP**"""

from tqdm import tqdm
import torch
import torch.nn as nn
import torch.optim as optim
import time
import json
import lpips
import os

ckpt_dir = "/content/drive/MyDrive/Special_Topic/checkpoints_guess_film3"
os.makedirs(ckpt_dir, exist_ok=True)

def train_one_epoch_stage1(
    G1, dataloader,
    opt_G1,
    criterionL1, perceptual, criterionSobelEdgeLoss, criterionLaplacianEdgeLoss,
    device, epoch, scaler,
    parser, skin_alpha=0.6, skin_steps=10, skin_sigma=1.5, skin_thresh=None
):
    G1.train()
    total_loss_G = 0.0
    total_loss_L1 = 0.0
    total_loss_content = 0.0
    total_loss_SobelEdge = 0.0
    total_loss_LaplacianEdge = 0.0

    # image=GT原圖, image2=修圖(條件)
    for image, image2 in dataloader:
        # -----------------
        # ---- 模型輸出 ----
        # -----------------
        image = image.to(device, non_blocking=True)
        image2 = image2.to(device, non_blocking=True)

        # -----------------
        # ---- 修圖先反模糊 ----
        with torch.no_grad():
            # 1. 用修圖圖抓臉部皮膚區域（哪裡被磨皮就在哪裡修）
            skin_mask = get_skin_mask(parser, to01(image2))
            m3 = skin_mask.expand_as(image2)
            # 2. 先對整張 image2 做反磨皮
            full = desoften(image2, alpha=0.3, steps=5, sigma=0.7)
            # 3. 只在臉部區域套用反磨皮，其他地方保留原圖
            image2 = image2 * (1 - m3) + full * m3


        # -----------------
        # ---- 計算Loss ----
        # -----------------
        opt_G1.zero_grad()

        with torch.amp.autocast('cuda'):
            image_coarse = G1(image2)

            l_l1 = criterionL1(image_coarse, image)
            loss_content = sum(perceptual(image_coarse, image))
            loss_SobelEdge = criterionSobelEdgeLoss(image_coarse, image)
            loss_LaplacianEdge = criterionLaplacianEdgeLoss(image_coarse, image)

            loss_g = (10.0 * l_l1
                      + 1.0 * loss_content
                      + 2.0 * loss_SobelEdge
                      + 1.0 * loss_LaplacianEdge)
        scaler.scale(loss_g).backward()
        scaler.step(opt_G1)

        # ======================
        #   4. 更新 scaler
        # ======================
        scaler.update()

        # -----------------
        # ---- 統計Loss ----
        # -----------------
        total_loss_G += loss_g.item()
        total_loss_L1 += l_l1.item()
        total_loss_content += loss_content.item()
        total_loss_SobelEdge += loss_SobelEdge.item()
        total_loss_LaplacianEdge += loss_LaplacianEdge.item()

    n = len(dataloader)
    print(f"Epoch [{epoch+1:2d}] | G_loss: {total_loss_G/n:.4f} "
        f"(L1: {total_loss_L1/n:.4f}, Content: {total_loss_content/n:.4f}, "
        f"Sobel: {total_loss_SobelEdge/n:.4f}, Lap: {total_loss_LaplacianEdge/n:.4f})")

def train_one_epoch_stage2_refine(
    G1, G2, D2, dataloader,
    opt_G1_small, opt_G2, opt_D2,
    criterionL1, lpips_fn, criterionSobelEdgeLoss, criterionLaplacianEdgeLoss,
    criterionGAN, criterionResidualLoss, criterionPerceptualLoss,
    device, epoch, scaler,
    parser, skin_alpha=0.6, skin_steps=10, skin_sigma=1.5, skin_thresh=None
):
    G1.train()
    G2.train()
    D2.train()

    total_loss_D = 0.0
    total_loss_G1 = 0.0
    total_loss_G2 = 0.0
    total_loss_G1_L1 = 0.0
    total_loss_G1_perc = 0.0
    total_loss_G1_edge = 0.0
    total_loss_G2_L1 = 0.0
    total_loss_G2_GAN = 0.0
    total_loss_G2_LPIPS = 0.0
    total_loss_G2_res = 0.0
    total_loss_G2_edge = 0.0
    total_loss_G2_skin = 0.0

    for image, image2 in dataloader:
        image  = image.to(device, non_blocking=True)
        image2 = image2.to(device, non_blocking=True)

        with torch.no_grad():
            # 1. 用修圖圖抓臉部皮膚區域（哪裡被磨皮就在哪裡修）
            skin_mask = get_skin_mask(parser, to01(image2))
            m3 = skin_mask.expand_as(image2)
            # 2. 先對整張 image2 做反磨皮
            full = desoften(image2, alpha=0.3, steps=5, sigma=0.7)
            # 3. 只在臉部區域套用反磨皮，其他地方保留原圖
            image2 = image2 * (1 - m3) + full * m3


        # ======================
        #   1. 更新 D2
        # ======================
        opt_D2.zero_grad()

        with torch.amp.autocast('cuda'):
            y_coarse = G1(image2).detach()
            with torch.no_grad():
                y_hat, _= G2(image2, y_coarse)

            d_real, feats_real = D2(torch.cat([image2, image], 1), return_feats=True)
            loss_D_real = criterionGAN(d_real, 1.)
            d_fake, _ = D2(torch.cat([image2, y_hat.detach()], 1), return_feats=True)
            loss_D_fake = criterionGAN(d_fake, 0.)
            loss_d = (loss_D_real + loss_D_fake) / 2.

        scaler.scale(loss_d).backward()
        scaler.step(opt_D2)

        feats_real_detached = [f.detach() for f in feats_real]

        # ======================
        #   2. 更新 G1 (只結構)
        # ======================
        opt_G1_small.zero_grad()

        with torch.amp.autocast('cuda'):
            y_coarse = G1(image2)

            l1_g1 = criterionL1(y_coarse, image)
            # perc_g1 = sum(criterionPerceptualLoss(y_coarse, image))
            edge_g1 = criterionSobelEdgeLoss(y_coarse, image) + 0.5 * criterionLaplacianEdgeLoss(y_coarse, image)

            loss_g = 10.0 * l1_g1 + 2.0 * edge_g1

        scaler.scale(loss_g).backward()
        scaler.step(opt_G1_small)

        # ======================
        #   3. 更新 G2 (質感)
        # ======================
        opt_G2.zero_grad()

        with torch.amp.autocast('cuda'):
            y_coarse = G1(image2).detach()
            y_hat, r = G2(image2, y_coarse)

            d_out_fake_G, feats_fake_G = D2(torch.cat([image2, y_hat], 1), return_feats=True)
            l_gan = criterionGAN(d_out_fake_G, 1.)

            l_lpips = lpips_fn(y_hat, image).mean()
            l_res, l1_g2 = criterionResidualLoss(r, y_hat, image, y_coarse)
            edge_g2 = criterionSobelEdgeLoss(y_hat, image) + 0.5 * criterionLaplacianEdgeLoss(y_hat, image)

            l_fm = feature_matching_loss(feats_fake_G, feats_real_detached)

            loss_G2 = (1.0 * l_gan
                      + 7.0 * l_lpips
                      + 5.0 * l1_g2
                      + 5.0 * l_res
                      + 4.0 * edge_g2
                      + 2.0 * l_fm)

        scaler.scale(loss_G2).backward()
        scaler.step(opt_G2)

        # ======================
        #   4. 更新 scaler
        # ======================
        scaler.update()

        # -----------------
        # ---- 統計 Loss ----
        # -----------------
        total_loss_G2_skin += L_skin.item()

        total_loss_D   += loss_d.item()
        total_loss_G1  += loss_g.item()
        total_loss_G2  += loss_G2.item()

        total_loss_G1_L1   += l1_g1.item()
        total_loss_G1_edge += edge_g1.item()

        total_loss_G2_L1   += l1_g2.item()
        total_loss_G2_GAN  += l_gan.item()
        total_loss_G2_LPIPS+= l_lpips.item()
        total_loss_G2_res  += l_res.item()
        total_loss_G2_edge += edge_g2.item()

    n = len(dataloader)
    print(
        f"Epoch [{epoch+1:2d}] | "
        f"D_loss: {total_loss_D/n:.4f} | "
        f"G1_loss: {total_loss_G1/n:.4f} "
        f"(L1: {total_loss_G1_L1/n:.4f}, Edge: {total_loss_G1_edge/n:.4f}) | "
        f"G2_loss: {total_loss_G2/n:.4f} "
        f"(L1: {total_loss_G2_L1/n:.4f}, "
        f"GAN: {total_loss_G2_GAN/n:.4f}, "
        f"LPIPS: {total_loss_G2_LPIPS/n:.4f}, "
        f"Res: {total_loss_G2_res/n:.4f}, "
        f"Edge: {total_loss_G2_edge/n:.4f}, "
        f"Skin: {total_loss_G2_skin/n:.4f}, "
    )

def train_one_epoch_joint(
    G1, G2, D2, dataloader,
    opt_G1, opt_G2, opt_D2,
    criterionL1, lpips_fn, criterionSobelEdgeLoss, criterionLaplacianEdgeLoss,
    criterionGAN, criterionResidualLoss, criterionPerceptualLoss,
    device, epoch, scaler,
    parser, skin_alpha=0.6, skin_steps=10, skin_sigma=1.5, skin_thresh=None
):
    G1.train()
    G2.train()
    D2.train()
    total_loss_D = 0.0
    total_loss_G1 = 0.0
    total_loss_G2 = 0.0
    total_loss_G1_L1 = 0.0
    total_loss_G1_perc = 0.0
    total_loss_G1_edge = 0.0
    total_loss_G2_L1 = 0.0
    total_loss_G2_GAN = 0.0
    total_loss_G2_LPIPS = 0.0
    total_loss_G2_res = 0.0
    total_loss_G2_edge = 0.0
    total_loss_G2_skin = 0.0  # 先在外面初始化

    # image是原圖 image2是修圖
    for image, image2 in dataloader:
        image  = image.to(device, non_blocking=True)
        image2 = image2.to(device, non_blocking=True)

        with torch.no_grad():
            # 1. 用修圖圖抓臉部皮膚區域（哪裡被磨皮就在哪裡修）
            skin_mask = get_skin_mask(parser, to01(image2))
            m3 = skin_mask.expand_as(image2)
            # 2. 先對整張 image2 做反磨皮
            full = desoften(image2, alpha=0.3, steps=5, sigma=0.7)
            # 3. 只在臉部區域套用反磨皮，其他地方保留原圖
            image2 = image2 * (1 - m3) + full * m3

        # ======================
        #   1. 更新 D2
        # ======================
        opt_D2.zero_grad()

        with torch.amp.autocast('cuda'):
            y_coarse = G1(image2).detach()
            with torch.no_grad():
                y_hat, r = G2(image2, y_coarse)

            d_real, feats_real = D2(torch.cat([image2, image], 1), return_feats=True)
            loss_D_real = criterionGAN(d_real, 1.)
            d_fake, _ = D2(torch.cat([image2, y_hat.detach()], 1), return_feats=True)
            loss_D_fake = criterionGAN(d_fake, 0.)
            loss_d = (loss_D_real + loss_D_fake) / 2.

        scaler.scale(loss_d).backward()
        scaler.step(opt_D2)

        feats_real_detached = [f.detach() for f in feats_real]

        # ======================
        #   2. 更新 G1 (只結構)
        # ======================
        opt_G1.zero_grad()

        with torch.amp.autocast('cuda'):
            y_coarse = G1(image2)

            l1_g1 = criterionL1(y_coarse, image)
            # perc_g1 = sum(criterionPerceptualLoss(y_coarse, image))
            edge_g1 = criterionSobelEdgeLoss(y_coarse, image) + 0.5 * criterionLaplacianEdgeLoss(y_coarse, image)

            loss_g = 10.0 * l1_g1 + 2.0 * edge_g1

        scaler.scale(loss_g).backward()
        scaler.step(opt_G1)

        # ======================
        #   3. 更新 G2 (質感)
        # ======================
        opt_G2.zero_grad()

        with torch.amp.autocast('cuda'):
            y_coarse = G1(image2).detach()
            y_hat, r = G2(image2, y_coarse)

            d_out_fake_G, feats_fake_G = D2(torch.cat([image2, y_hat], 1), return_feats=True)
            l_gan = criterionGAN(d_out_fake_G, 1.)

            l_lpips = lpips_fn(y_hat, image).mean()
            l_res, l1_g2 = criterionResidualLoss(r, y_hat, image, y_coarse)
            edge_g2 = criterionSobelEdgeLoss(y_hat, image) + 0.5 * criterionLaplacianEdgeLoss(y_hat, image)

            l_fm = feature_matching_loss(feats_fake_G, feats_real_detached)

            loss_G2 = (1.0 * l_gan
                      + 7.0 * l_lpips
                      + 5.0 * l1_g2
                      + 5.0 * l_res
                      + 4.0 * edge_g2
                      + 2.0 * l_fm)

        scaler.scale(loss_G2).backward()
        scaler.step(opt_G2)

        # ======================
        #   4. 更新 scaler
        # ======================
        scaler.update()

        # -----------------
        # ---- 統計 Loss ----
        # -----------------
        total_loss_G2_skin += L_skin.item()

        total_loss_D   += loss_d.item()
        total_loss_G1  += loss_g.item()
        total_loss_G2  += loss_G2.item()

        total_loss_G1_L1   += l1_g1.item()

        total_loss_G1_edge += edge_g1.item()

        total_loss_G2_L1   += l1_g2.item()
        total_loss_G2_GAN  += l_gan.item()
        total_loss_G2_LPIPS+= l_lpips.item()
        total_loss_G2_res  += l_res.item()
        total_loss_G2_edge += edge_g2.item()

    n = len(dataloader)
    print(
        f"Epoch [{epoch+1:2d}] | "
        f"D_loss: {total_loss_D/n:.4f} | "
        f"G1_loss: {total_loss_G1/n:.4f} "
        f"(L1: {total_loss_G1_L1/n:.4f}, Edge: {total_loss_G1_edge/n:.4f}) | "
        f"G2_loss: {total_loss_G2/n:.4f} "
        f"(L1: {total_loss_G2_L1/n:.4f}, "
        f"GAN: {total_loss_G2_GAN/n:.4f}, "
        f"LPIPS: {total_loss_G2_LPIPS/n:.4f}, "
        f"Res: {total_loss_G2_res/n:.4f}, "
        f"Edge: {total_loss_G2_edge/n:.4f}, "
        f"Skin: {total_loss_G2_skin/n:.4f}, "
    )

"""# **訓練**"""

# 準備模型
G1 = Generator(in_num_ch=3, out_num_ch=3).to(device)

G2 = RRDBRefineNet(in_nc=6, out_nc=3, nf=32, nb=3, gc=32).to(device)

D2 = Discriminator(in_num_ch=6, first_num_ch=32).to(device)

# Optimizers
opt_G1_warm = optim.Adam(G1.parameters(), lr=1e-4, betas=(0.5,0.999))
opt_G1_small = optim.Adam(G1.parameters(), lr=1e-5, betas=(0.5,0.999))
opt_G1_joint = optim.Adam(G1.parameters(), lr=1e-5, betas=(0.5,0.999))

opt_G2 = optim.Adam(G2.parameters(), lr=1e-4, betas=(0.5,0.999))
opt_G2_joint= optim.Adam(G2.parameters(), lr=1e-5, betas=(0.5,0.999))

opt_D2 = optim.Adam(D2.parameters(), lr=1e-6, betas=(0.5,0.999))
opt_D2_joint = optim.Adam(D2.parameters(), lr=1e-6, betas=(0.5,0.999))

# Losses
criterionL1 = nn.L1Loss().to(device)
criterionGAN = GANLoss(device, ls_gan=True).to(device)
criterionPerceptualLoss = PerceptualLoss(device, content_layers=['conv_2','conv_3']).to(device)

criterionResidualLoss = ResidualLoss(nn.L1Loss()).to(device)
criterionSobelEdgeLoss = SobelEdgeLoss(mode='mag', loss='l1').to(device)
criterionLaplacianEdgeLoss = LaplacianEdgeLoss(loss='l1').to(device)

lpips_fn = lpips.LPIPS(net='alex').to(device).eval()

scaler = torch.amp.GradScaler('cuda')

# ======================
#   第一階段
# ======================
for epoch in range(30):
    start = time.time()
    train_one_epoch_stage1(G1, train_loader,
        opt_G1_warm,
        criterionL1, criterionPerceptualLoss, criterionSobelEdgeLoss, criterionLaplacianEdgeLoss,
        device, epoch, scaler,
        parser, 0.6, 10, 1.5, None
    )
    end = time.time()
    print(f"Epoch {epoch} 花費時間: {(end - start)/60:.2f} 分鐘")

    if (epoch + 1) % 10 == 0:
        torch.save({
            "epoch": epoch,
            "G1": G1.state_dict(),
            "opt_G1_warm": opt_G1_warm.state_dict(),
            "scaler": scaler.state_dict(),
        }, f"{ckpt_dir}/stage1_e{epoch}.pth")
        print(f"[Stage1] resume checkpoint saved at epoch {epoch}")

# ======================
#   第二階段
# ======================
for p in G1.parameters():
    p.requires_grad = True

for epoch in range(30):
    start = time.time()
    train_one_epoch_stage2_refine(
        G1, G2, D2, train_loader,
        opt_G1_small, opt_G2, opt_D2,
        criterionL1, lpips_fn, criterionSobelEdgeLoss, criterionLaplacianEdgeLoss,
        criterionGAN, criterionResidualLoss, criterionPerceptualLoss,
        device, epoch, scaler,
        parser, 0.6, 10, 1.5, None
    )
    end = time.time()
    print(f"Epoch {epoch} 花費時間: {(end - start)/60:.2f} 分鐘")

    if (epoch + 1) % 10 == 0:
        torch.save({
            "epoch": epoch,
            "G1": G1.state_dict(),
            "G2": G2.state_dict(),
            "D2": D2.state_dict(),
            "opt_G1_small": opt_G1_small.state_dict(),
            "opt_G2": opt_G2.state_dict(),
            "opt_D2": opt_D2.state_dict(),
            "scaler": scaler.state_dict(),
        }, f"{ckpt_dir}/stage2_e{epoch}.pth")
        print(f"[Stage2] resume checkpoint saved at epoch {epoch}")

# ======================
#   第三階段
# ======================
for epoch in range(30):
    start = time.time()
    train_one_epoch_joint(
        G1, G2, D2, train_loader,
        opt_G1_joint, opt_G2_joint, opt_D2_joint,
        criterionL1, lpips_fn, criterionSobelEdgeLoss, criterionLaplacianEdgeLoss,
        criterionGAN, criterionResidualLoss, criterionPerceptualLoss,
        device, epoch, scaler,
        parser, 0.6, 10, 1.5, None
    )
    end = time.time()
    print(f"Epoch {epoch} 花費時間: {(end - start)/60:.2f} 分鐘")

    if (epoch + 1) % 10 == 0:
        torch.save({
            "epoch": epoch,
            "G1": G1.state_dict(),
            "G2": G2.state_dict(),
            "D2": D2.state_dict(),
            "opt_G1_joint": opt_G1_joint.state_dict(),
            "opt_G2_joint": opt_G2_joint.state_dict(),
            "opt_D2_joint": opt_D2_joint.state_dict(),
            "scaler": scaler.state_dict(),
        }, f"{ckpt_dir}/stage3_e{epoch}.pth")
        print(f"[Stage3] resume checkpoint saved at epoch {epoch}")

"""# **用自己的照片測試**"""

import torch
from torchvision import transforms
from PIL import Image

transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

ckpt = torch.load("/content/drive/MyDrive/Special_Topic/checkpoints_guss/stage3_e29.pth",
                  map_location=device)

G1 = Generator(in_num_ch=3, out_num_ch=3).to(device)
G2 = RRDBRefineNet(in_nc=6, out_nc=3, nf=32, nb=3, gc=32).to(device)

G1.load_state_dict(ckpt["G1"])
G2.load_state_dict(ckpt["G2"])

G1.eval()
G2.eval()

img_path ="w5.png"   # 修圖路徑
img = Image.open(img_path).convert("RGB")
img_tensor = transform(img).unsqueeze(0).to(device)


gt_path = "w2.png"   # 原圖路徑
gt = Image.open(gt_path).convert("RGB")
gt_tensor = transform(gt).unsqueeze(0).to(device)

"""比較模型輸出"""

import torch
from torchvision import transforms
import matplotlib.pyplot as plt
import lpips
from torchvision.utils import save_image

G1.eval(); G2.eval()
criterionL1 = nn.L1Loss().to(device)
criterionGAN = GANLoss(device, ls_gan=True).to(device)
criterionPerceptualLoss = PerceptualLoss(device, content_layers=['conv_2','conv_3']).to(device).eval()

criterionResidualLoss = ResidualLoss(nn.L1Loss()).to(device)
criterionSobelEdgeLoss = SobelEdgeLoss(mode='mag', loss='l1').to(device)
criterionLaplacianEdgeLoss = LaplacianEdgeLoss(loss='l1').to(device)
lpips_fn = lpips.LPIPS(net='alex').to(device).eval()

with torch.no_grad():
    img_tensor = img_tensor.to(device)
    gt_tensor  = gt_tensor.to(device)

    with torch.no_grad():
        skin_mask = get_skin_mask(parser, to01(img_tensor))
        m3 = skin_mask.expand_as(img_tensor)
        full = desoften(img_tensor, alpha=0.3, steps=5, sigma=0.7)
        cond_G1 = img_tensor*(1 - m3) + full*m3

    y_coarse = G1(cond_G1)
    y_hat, r = G2(cond_G1, y_coarse)

    l1 = criterionL1(y_hat, gt_tensor)
    sobel = criterionSobelEdgeLoss(y_hat, gt_tensor)
    lap   = criterionLaplacianEdgeLoss(y_hat, gt_tensor)
    lp  = lpips_fn(y_hat, gt_tensor, normalize=True).mean()
    l_res, l1_final = criterionResidualLoss(r, y_hat, gt_tensor, y_coarse)

    eval_score_stage1 = 10.0*l1 + 2.0*sobel + 1.0*lap
    eval_score_stage2 = 1.0*lp + 5.0*l1_final + 5.0*l_res + 4.0*(sobel+0.5*lap)

    print({
      "L1": f"{l1:.4f}",
      "Sobel": f"{sobel:.4f}",
      "Laplacian": f"{lap:.4f}",
      "LPIPS": f"{lp:.4f}",
      "Res": f"{l_res:.4f}",
      "L1_final": f"{l1_final:.4f}",
      "EvalStage1": f"{eval_score_stage1:.4f}",
      "EvalStage2": f"{eval_score_stage2:.4f}"
    })


# ======================
#   在下方顯示圖片
# ======================
vis = y_hat.detach().cpu()
if vis.dim() == 4:
    vis = vis[0]
vis = (vis * 0.5 + 0.5).clamp(0, 1)

to_pil = transforms.ToPILImage()
out_img = to_pil(vis)
plt.figure(figsize=(6,6)); plt.imshow(out_img); plt.axis('off'); plt.show()
out_img.save("復原_yAyG.png")

import torch
from torchvision import transforms
import matplotlib.pyplot as plt
import lpips

G1.eval(); G2.eval()
criterionL1 = nn.L1Loss().to(device)
criterionPerceptualLoss = PerceptualLoss(device, content_layers=['conv_2','conv_3']).to(device).eval()
criterionSobelEdgeLoss = SobelEdgeLoss(mode='mag', loss='l1').to(device)
criterionLaplacianEdgeLoss = LaplacianEdgeLoss(loss='l1').to(device)
lpips_fn = lpips.LPIPS(net='alex').to(device).eval()

with torch.no_grad():
    img_tensor = img_tensor.to(device)
    gt_tensor  = gt_tensor.to(device)

    l1_edit = criterionL1(img_tensor, gt_tensor)
    sobel_edit = criterionSobelEdgeLoss(img_tensor, gt_tensor)
    lap_edit   = criterionLaplacianEdgeLoss(img_tensor, gt_tensor)
    lp_edit = lpips_fn(img_tensor, gt_tensor, normalize=True).mean()

    eval_edit = 10.0*l1_edit + 2.0*sobel_edit + 1.0*lap_edit

    print({
        "EDIT_vs_GT_L1":      f"{l1_edit:.4f}",
        "EDIT_vs_GT_Sobel":   f"{sobel_edit:.4f}",
        "EDIT_vs_GT_Lap":     f"{lap_edit:.4f}",
        "EDIT_vs_GT_LPIPS":   f"{lp_edit:.4f}",
        "EDIT_vs_GT_Eval":    f"{eval_edit:.4f}",
    })

"""# **抓模塊輸出**

## **抓pix2pix**
"""

feature_maps = {}

def save_feature_map(name):
    def hook(model, input, output):
        feature_maps[name] = output.detach().cpu()
    return hook

G1.down_1.register_forward_hook(save_feature_map('down_1'))
G1.down_2.register_forward_hook(save_feature_map('down_2'))
G1.down_3.register_forward_hook(save_feature_map('down_3'))
G1.down_4.register_forward_hook(save_feature_map('down_4'))
G1.down_5.register_forward_hook(save_feature_map('down_5'))
G1.down_6.register_forward_hook(save_feature_map('down_6'))

G1.bottleneck.register_forward_hook(save_feature_map('bottleneck'))

G1.up_1.register_forward_hook(save_feature_map('up_1'))
G1.up_2.register_forward_hook(save_feature_map('up_2'))
G1.up_3.register_forward_hook(save_feature_map('up_3'))
G1.up_4.register_forward_hook(save_feature_map('up_4'))
G1.up_5.register_forward_hook(save_feature_map('up_5'))

with torch.no_grad():
    img_tensor = img_tensor.to(device)
    gt_tensor  = gt_tensor.to(device)

    with torch.no_grad():
        skin_mask = get_skin_mask(parser, to01(img_tensor))
        m3 = skin_mask.expand_as(img_tensor)
        full = desoften(img_tensor, alpha=1, steps=12, sigma=2)
        cond_G1 = img_tensor*(1 - m3) + full*m3

    out = G1(cond_G1)

import matplotlib.pyplot as plt

def visualize_feature_map(fm, num=8):
    fm = fm[0]   # 第 0 batch
    fm = fm[:num]  # 前 num 個 channel

    fig, axes = plt.subplots(1, num, figsize=(16,3))
    for i in range(num):
        axes[i].imshow(fm[i], cmap='gray')
        axes[i].axis('off')
    plt.show()

visualize_feature_map(feature_maps['down_1'])
visualize_feature_map(feature_maps['bottleneck'])
visualize_feature_map(feature_maps['up_3'])

"""## **抓RRDB**"""

feature_maps = {}

def save_feature_map(name):
    def hook(module, input, output):
        feature_maps[name] = output.detach().cpu()
    return hook

def register_rdb_hooks(rdb: ResidualDenseBlock_5C, prefix: str):
    rdb.conv1.register_forward_hook(save_feature_map(f"{prefix}_conv1"))
    rdb.conv2.register_forward_hook(save_feature_map(f"{prefix}_conv2"))
    rdb.conv3.register_forward_hook(save_feature_map(f"{prefix}_conv3"))
    rdb.conv4.register_forward_hook(save_feature_map(f"{prefix}_conv4"))
    rdb.conv5.register_forward_hook(save_feature_map(f"{prefix}_conv5"))
    rdb.cbma.register_forward_hook(save_feature_map(f"{prefix}_cbam"))

# 1. head: 把 [x, y_coarse] 投影到 nf 維度的地方
G2.head.register_forward_hook(save_feature_map("head"))
# 2. RRDB 幹線：trunk 是一個 nn.Sequential
for i, rrdb in enumerate(G2.trunk):
    rrdb.register_forward_hook(save_feature_map(f"RRDB_{i+1}"))
# 3. 幹線卷積
G2.trunk_conv.register_forward_hook(save_feature_map("trunk_conv"))
# 4. tail: 輸出的 residual r（還沒加回 y_coarse）
G2.tail.register_forward_hook(save_feature_map("tail_r"))
G2.trunk[0].b1.register_forward_hook(save_feature_map("RRDB1_b1_out"))

for i, rrdb in enumerate(G2.trunk):
    k = i + 1
    register_rdb_hooks(rrdb.b1, f"RRDB{k}_b1")
    register_rdb_hooks(rrdb.b2, f"RRDB{k}_b2")
    register_rdb_hooks(rrdb.b3, f"RRDB{k}_b3")

with torch.no_grad():
    img_tensor = img_tensor.to(device)
    gt_tensor  = gt_tensor.to(device)

    with torch.no_grad():
        skin_mask = get_skin_mask(parser, to01(img_tensor))
        m3 = skin_mask.expand_as(img_tensor)
        full = desoften(img_tensor, alpha=1, steps=12, sigma=2)
        cond_G1 = img_tensor*(1 - m3) + full*m3

    y_coarse = G1(cond_G1).detach()
    y_hat, r = G2(img_tensor, y_coarse)

print(feature_maps.keys())

def visualize_feature_map(fm, title="", num_channels=8):
    fm = fm[0]
    C = fm.size(0)
    num = min(num_channels, C)

    fig, axes = plt.subplots(1, num, figsize=(3*num,3))
    if num == 1:
        axes = [axes]

    for i in range(num):
        fmap = fm[i]
        fmap_min = fmap.min()
        fmap_max = fmap.max()
        fmap_norm = (fmap - fmap_min) / (fmap_max - fmap_min + 1e-6)
        axes[i].imshow(fmap_norm.numpy(), cmap="gray")
        axes[i].axis("off")
        axes[i].set_title(f"ch {i}")
    plt.suptitle(title)
    plt.tight_layout()
    plt.show()

visualize_feature_map(feature_maps["head"],        "Head: [x, y_coarse] → nf")
visualize_feature_map(feature_maps["RRDB_1"],      "RRDB Block 1 Output")
visualize_feature_map(feature_maps["RRDB1_b1_cbam"], "RRDB1 b1 after CBAM")
visualize_feature_map(feature_maps["trunk_conv"],  "Trunk Conv")
visualize_feature_map(feature_maps["tail_r"],      "Residual r (要加回去的紋理)")
visualize_feature_map(feature_maps["RRDB1_b1_out"], "RRDB1 b1 (ResidualDenseBlock_5C output)")

"""## **抓CBAM**"""

feature_maps = {}

def save_feature_map(name):
    def hook(module, input, output):
        feature_maps[name] = output.detach().cpu()
    return hook

def register_rdb_hooks(rdb: ResidualDenseBlock_5C, prefix: str):
    rdb.conv1.register_forward_hook(save_feature_map(f"{prefix}_conv1"))
    rdb.conv2.register_forward_hook(save_feature_map(f"{prefix}_conv2"))
    rdb.conv3.register_forward_hook(save_feature_map(f"{prefix}_conv3"))
    rdb.conv4.register_forward_hook(save_feature_map(f"{prefix}_conv4"))
    rdb.conv5.register_forward_hook(save_feature_map(f"{prefix}_conv5"))

    # CBAM 輸出後的特徵
    rdb.cbma.register_forward_hook(save_feature_map(f"{prefix}_cbam_out"))

    # ❶ Channel Attention 的權重 Mc: (B,C,1,1)
    rdb.cbma.channel_attention.register_forward_hook(
        save_feature_map(f"{prefix}_ca")
    )

    # ❷ Spatial Attention 的權重 Ms: (B,1,H,W)
    rdb.cbma.spatial_attention.register_forward_hook(
        save_feature_map(f"{prefix}_sa")
    )


# 1. head: 把 [x, y_coarse] 投影到 nf 維度的地方
G2.head.register_forward_hook(save_feature_map("head"))
# 2. RRDB 幹線：trunk 是一個 nn.Sequential
for i, rrdb in enumerate(G2.trunk):
    rrdb.register_forward_hook(save_feature_map(f"RRDB_{i+1}"))
# 3. 幹線卷積
G2.trunk_conv.register_forward_hook(save_feature_map("trunk_conv"))
# 4. tail: 輸出的 residual r（還沒加回 y_coarse）
G2.tail.register_forward_hook(save_feature_map("tail_r"))
G2.trunk[0].b1.register_forward_hook(save_feature_map("RRDB1_b1_out"))

for i, rrdb in enumerate(G2.trunk):
    k = i + 1
    register_rdb_hooks(rrdb.b1, f"RRDB{k}_b1")
    register_rdb_hooks(rrdb.b2, f"RRDB{k}_b2")
    register_rdb_hooks(rrdb.b3, f"RRDB{k}_b3")

with torch.no_grad():
    img_tensor = img_tensor.to(device)
    gt_tensor  = gt_tensor.to(device)

    with torch.no_grad():
        skin_mask = get_skin_mask(parser, to01(img_tensor))
        m3 = skin_mask.expand_as(img_tensor)
        full = desoften(img_tensor, alpha=1, steps=12, sigma=2)
        cond_G1 = img_tensor*(1 - m3) + full*m3

    y_coarse = G1(cond_G1).detach()
    y_hat, r = G2(img_tensor, y_coarse)

print(feature_maps.keys())

import cv2
import numpy as np
import torch.nn.functional as F
from PIL import Image

def visualize_spatial_attention_cv(att, orig_img_pil, title="CBAM Spatial Attention (CV2)"):
    # # 這裡 att 是 feature_maps[...]，shape: (B,1,H',W')
    att = att[0, 0]   # (H', W')
    att = (att - att.min()) / (att.max() - att.min() + 1e-6)

    H, W = orig_img_pil.size[1], orig_img_pil.size[0]
    att_up = F.interpolate(
        att.unsqueeze(0).unsqueeze(0),
        size=(H, W),
        mode="bilinear",
        align_corners=False
    )[0, 0].cpu().numpy()  # (H,W) in [0,1]

    # 轉成 0~255 uint8
    att_uint8 = np.uint8(att_up * 255)

    # 變成彩色 heatmap (JET)
    heatmap = cv2.applyColorMap(att_uint8, cv2.COLORMAP_JET)  # (H,W,3), BGR

    # 原圖轉成 OpenCV 用的 BGR
    img_bgr = cv2.cvtColor(np.array(orig_img_pil.convert("RGB")), cv2.COLOR_RGB2BGR)

    # 疊圖：alpha 越大 heatmap 越明顯
    overlay = cv2.addWeighted(heatmap, 0.5, img_bgr, 0.5, 0)

    # 轉回 RGB 給 matplotlib 顯示
    overlay_rgb = cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(4,4))
    plt.imshow(overlay_rgb)
    plt.axis("off")
    plt.title(title)
    plt.show()

    print("sa min / max / mean:", att.min().item(), att.max().item(), att.mean().item())


# ---- 這裡改成「自動抓最後一個 RRDB 的 b3」 ----

orig_img_pil = Image.open(gt_path).convert("RGB")

last_idx = len(G2.trunk)                 # 比如 trunk 有 3 個 RRDB，這裡就是 3
sa_key = f"RRDB1_b2_sa"        # "RRDB3_b3_sa"

print("using key:", sa_key)

visualize_spatial_attention_cv(
    feature_maps[sa_key],
    orig_img_pil,
    title=f"RRDB{last_idx} b3 CBAM Spatial Attention (closest to output)"
)

def visualize_channel_attention(ca, title="Channel Attention"):
    """
    ca: feature_maps["RRDB1_b1_ca"], shape (B,C,1,1)
    """
    w = ca[0, :, 0, 0].numpy()   # (C,)
    plt.figure(figsize=(6,3))
    plt.bar(range(len(w)), w)
    plt.ylim(0, 1)
    plt.title(title)
    plt.xlabel("Channel index")
    plt.ylabel("Weight")
    plt.show()

visualize_channel_attention(feature_maps["RRDB1_b1_ca"], "RRDB1 b1 Channel Attention")

"""# **Demo**"""

import torch
import torch.nn as nn
from torchvision import transforms
import lpips
from PIL import Image

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
G1.to(device).eval()
G2.to(device).eval()

criterionL1 = nn.L1Loss().to(device)
criterionGAN = GANLoss(device, ls_gan=True).to(device)
criterionPerceptualLoss = PerceptualLoss(
    device, content_layers=['conv_2', 'conv_3']
).to(device).eval()

criterionResidualLoss = ResidualLoss(nn.L1Loss()).to(device)
criterionSobelEdgeLoss = SobelEdgeLoss(mode='mag', loss='l1').to(device)
criterionLaplacianEdgeLoss = LaplacianEdgeLoss(loss='l1').to(device)
lpips_fn = lpips.LPIPS(net='alex').to(device).eval()

to_tensor = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor(),
    transforms.Normalize(0.5, 0.5),
])
to_pil = transforms.ToPILImage()


def run_restore(
    edit_img: Image.Image,
    gt_img: Image.Image | None = None
):
    """
    edit_img: 修圖後的圖片 (PIL)
    gt_img:   原圖 (PIL，可為 None，沒有就只做還原、不算指標)
    """
    G1.eval()
    G2.eval()

    with torch.no_grad():
        img_tensor = to_tensor(edit_img).unsqueeze(0).to(device)
        if gt_img is not None:
            gt_tensor = to_tensor(gt_img).unsqueeze(0).to(device)
        else:
            gt_tensor = None

        skin_mask = get_skin_mask(parser, to01(img_tensor))
        if skin_mask.shape[1] == 1:
            m3 = skin_mask.expand_as(img_tensor)
        else:
            m3 = skin_mask
        full = desoften(img_tensor, alpha=0.3, steps=5, sigma=0.7)
        cond_G1 = img_tensor * (1 - m3) + full * m3

        y_coarse = G1(cond_G1)
        y_hat, r = G2(cond_G1, y_coarse)

        metrics = {}
        if gt_tensor is not None:
            l1 = criterionL1(y_hat, gt_tensor)
            sobel = criterionSobelEdgeLoss(y_hat, gt_tensor)
            lap = criterionLaplacianEdgeLoss(y_hat, gt_tensor)
            lp = lpips_fn(y_hat, gt_tensor, normalize=True).mean()
            l_res, l1_final = criterionResidualLoss(r, y_hat, gt_tensor, y_coarse)

            eval_score_stage1 = 10.0*l1 + 2.0*sobel + 1.0*lap
            eval_score_stage2 = 1.0*lp + 5.0*l1_final + 5.0*l_res + 4.0*(sobel+0.5*lap)

            metrics = {
                "L1": float(l1.item()),
                "Sobel": float(sobel.item()),
                "Laplacian": float(lap.item()),
                "LPIPS": float(lp.item()),
                "Res": float(l_res.item()),
                "L1_final": float(l1_final.item()),
                "EvalStage1": float(eval_score_stage1.item()),
                "EvalStage2": float(eval_score_stage2.item())
            }

        vis = y_hat.detach().cpu()[0]
        vis = (vis * 0.5 + 0.5).clamp(0, 1)
        out_img = to_pil(vis)

    return out_img, metrics

import gradio as gr

def gradio_fn(edit_img):
    if edit_img is None:
        return None, None
    out_img, _ = run_restore(edit_img, None)

    return edit_img, out_img


with gr.Blocks() as demo:
    gr.Markdown("臉部修圖")
    run_btn = gr.Button("開始還原")
    gr.Markdown("### 修圖後（左） vs 還原後（右）")

    with gr.Row():
        left_img = gr.Image(
            label="修圖後（輸入）",
            type="pil"
        )
        # 右邊 = 還原輸出
        right_img = gr.Image(
            label="還原結果（輸出）",
            type="pil"
        )

    run_btn.click(
        fn=gradio_fn,
        inputs=[left_img],
        outputs=[left_img, right_img]
    )

demo.launch()